FROM rust:1.75 AS builder 
WORKDIR /app 
COPY Cargo.toml Cargo.lock ./
COPY src ./src 
COPY migrations ./migrations


RUN cargo build --release 

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/* 

WORKDIR /app 

COPY --from=builder /app/target/release/rusty-ecom /app/rusty-ecom
COPY --from=builder /app/migrations /app/migrations 

ENV DATABASE_URL=sqlite://ecom.db 

EXPORE 3000

CMD ["./rusty-ecom"]
